version: ~> 1.0
import:
  - form8ion/.travis-ci:node.yml
  - travi/.travis-ci:authenticated-semantic-release.yml
notifications:
  email: false
before_script:
  - npm ls >/dev/null
after_success: 'npm run coverage:report'
